### ISSUE TITLE
Complete port to Python 3

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Persistence#2]
Maybe including the C extension?

**Comment by hannosch** [comment]
As mentioned in zopefoundation/ExtensionClass#7, I think we should stick with pure-Python implementations only for Python 3 support. There shouldn't be any need to continue using C code here.

**Comment by hannosch** [comment]
Turns out the tox environment wasn't picking up all tests, switched to zope.testrunner in tox, and now you get local failures as well as in travis-ci.

**Comment by hannosch** [comment]
I've worked on this more at the recent Zope Sprint. We now have Persistence working under Python 2 with a C-based persistent and with a Python based persistent. It also works under Python 3 and PyPy with a Python based persistent.

In order to make it compatible with Python 3 and a C-based persistent, we need some changes to the persistent project. PR for that should be coming soon.

**Comment by hannosch** [comment]
I've picked up work again for a bit. Persistence master is now using ExtensionClass 4.2, which comes with a C extension ported to Python 3.

I've also created a py3-c-extension branch for Persistence based on this. On the branch I made some initial changes to port Persistence's own C extension to Python 3. It seems to compile, but there's probably still a bunch of problems with it.

Any help is welcome ;)

**Comment by hannosch** [comment]
@stephan-hof if you haven't seen this, I've started work on the C extension port. But I could definitely use some help to get this completed. I've only done copy/paste programming here, mirroring your changes done in ExtensionClass ;)

Branch is at https://github.com/zopefoundation/Persistence/tree/py3-c-extension
So far only one commit: 24ba294ff1c90a109d2da599629d0ca4b3dcaeb8

**Comment by stephan-hof** [comment]
Hi Hanno, I'll try to have a deeper look. By just looking at the change I think

* C-Extension is not imported because python3 uses absolute imports. So in `__init__.py` it must be `from ._Persistence import Persistent`
* `P_getattr` has a flaw, because `Py_FindAttr` gets the result of `convert_name`, which is always bytes. The bytes of `convert_name` are only needed to do some manual detections if unghost is needed. However in python3 `Py_FindAttr` needs native string (bytes in python2 and unicode in python3). It looks pretty similar to this code: https://github.com/zopefoundation/ExtensionClass/blob/master/src/ExtensionClass/_ExtensionClass.c#L402. So use the converted bytes internally and pass the `name` as it is to `Py_FindAttr`

I'll try to help more but my schedule for the next 3 weeks is full with other stuff.
So don't expect much until mid February (the same goes for C-Extension Acquisition btw.)

**Comment by hannosch** [comment]
The port should be done.

I've also cherry-picked 8593f3e7dbc4fc0027fe34fb15dd69c32c797461 from @MatthewWilkes to master and released that as part of 3.0a3.
